# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Pointcast-Mobile-App-desktop' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # pod 'GoogleMaps'
  # Pods for Pointcast-Mobile-App-desktop

end

target 'Pointcast-Mobile-App-mobile' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleMaps'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  # pod 'Firebase/Invites'
  pod 'Firebase/Crash'
  # Pods for Pointcast-Mobile-App-mobile
  pod 'SendBirdSDK'
  #pod 'AFNetworking'

end
